### ISSUE TITLE
Method signature not respected when having two methods with the same name

### ISSUE THREAD

**Issue by kongslund** [jiaqi/jmxterm#11]
We are trying to invoke a method on an MBean that have two methods defined
* `registerProcess(String, int)`
* `registerProcess(String, String)`

We want to invoke the second method but jmxterm always chooses the first method it sees having the correct name and number of arguments. It does not seem to take the actual method signature into consideration.

Any workaround to this?

This issue was observered with `jmxterm-1.0-alpha-4-uber.jar`

**Comment by wattazoum** [comment]
Hi, 
Shouldn't this issue be closed ?
