### ISSUE TITLE
get only value of java.lang:type=Memory HeapMemoryUsage used|committed|...

### ISSUE THREAD

**Issue by svenXY** [jiaqi/jmxterm#28]
Hi,

I'm trying to only get the value of java.lang:type=Memory HeapMemoryUsage.used.

The following does not work:
```shell
echo 'get used -s -b java.lang:type=Memory HeapMemoryUsage' | java -jar /tmp/jmxterm-1.0-alpha-4-uber.jar -l localhost:10006 -v silent -n
```

The result is 
```
{ 
  committed = 663617536;
  init = 62761024;
  max = 1908932608;
  used = 424752800;
 }
```

What I expected is
```
424752800
```

I'm not a java programmer, but a sysadmin trying to get these values into Zabbix.

Can you give me a clue?

Thanks,
Sven

**Comment by jiaqi** [comment]
I believe Stephan's change https://github.com/jiaqi/jmxterm/commit/8834e1e9d99b6dad390ea17a01b78e1f4eab9ff3 solved this problem. Can you verify? Thanks.

**Comment by dirk-olmes** [comment]
@svenXY if you're monitoring with Zabbix, why deal with jxmterm? Zabbix has native JMX monitoring using a java bridge ...

**Comment by svenXY** [comment]
Just for completeness:

yes, 8834e1e solved it, 
```bash
echo 'get -s -b java.lang:type=Memory HeapMemoryUsage.used' | java -jar jmxterm-1.0.0-SNAPSHOT-uber.jar -l localhost:10006 -v silent -n
```
now returns the correct value, thanks.

@dirk-olmes - yes, I know, works if ports are open. But we have to do it from local via agent.
