### ISSUE TITLE
include a license with the source code

### ISSUE THREAD

**Issue by activedecay** [jiaqi/jmxterm#35]
I created a pull request for this.

**Comment by cbaenziger** [comment]
Indeed! I'd love to look at this code but only can if it has a published license.

**Comment by aalku** [comment]
http://wiki.cyclopsgroup.org/jmxterm/index.html states this about the license: 

> jmxterm is an open source Java project under CyclopsGroup.org.

But we need more details about that license. Please create a LICENSE file stating if it's GPL3 or MIT, Apache or whatever.

Thank you

**Comment by activedecay** [comment]
Thank you!
