### ISSUE TITLE
Please create releases in github

### ISSUE THREAD

**Issue by attila123** [jiaqi/jmxterm#38]
Hi,
The project's wiki page points to this github repository for the source code (see http://wiki.cyclopsgroup.org/jmxterm/source.html).
However this github project does not have any releases. Without any releases it's not really possible (to easily) download the exact source code for a certain release. For example I need to download the source code for the 1.0 alpha 4 version (e.g. for legal check for a big company, which has a process for legal check, which requires the source code packages of open source components with their respective versions).
Apart from this, having releases of a software makes life easier anyway and this is how things normally work.
Please, please create a release at least for 1.0 alpha 4 version and for further releases!

**Comment by jiaqi** [comment]
This project used to live in sourceforge where you can find all the released files.
For 1.0-alpha-4
https://sourceforge.net/projects/cyclops-group/files/jmxterm/1.0-alpha-4/

**Comment by jumarko** [comment]
The releases on sourceforce are pretty old and there are many changes since then.
Any plans to make a new release?

**Comment by dirk-olmes** [comment]
+1 for a proper release. We still use the alpha-4 in production (without any trouble, though),

A proper release which does not have a scary "alpha" in it would be nicer, though.

**Comment by odoepner** [comment]
The current source code from github builds perfectly fine using a simple `mvn clean verify` and produces jmxterm-1.0.0-SNAPSHOT-uber.jar in the target folder. So if you want a "latest build", just build it yourself. :)

**Comment by jumarko** [comment]
@odoepner that's certainly true. 
However, most people want to get some kind of stable release instead of building latest version which many of us can consider somewhat unstable.
I guess most of the people will just download the alpha-4 version, anyway.
It'd be nice to get a proper release after so many years :).

**Comment by jiaqi** [comment]
Alright, I created a 1.0.0 release. It's not very different from the last alpha4 since there hasn't been many activities in the project.
https://github.com/jiaqi/jmxterm/releases/tag/v1.0.0

**Comment by odoepner** [comment]
Thank you! We use it now to talk to Apache Camel.
