### ISSUE TITLE
Support bean name with a space in it

### ISSUE THREAD

**Issue by blasd** [jiaqi/jmxterm#41]
This is related to https://github.com/jiaqi/jmxterm/issues/4

We have bean name holding a space in it. It seems not possible to fetch them. It would be nice if these could be protected by double-quotes for instance

**Comment by blasd** [comment]
To handle spaces in bean names, the space have to be prefixed by a '\' character.

**Comment by mkdika** [comment]
For name with space character you need to use backslash ('\') char as prefix:
ex: java.lang:name=G1 Old Gen,type=MemoryPool  ->  java.lang:name=G1\ Old\ Gen,type=MemoryPool

**Comment by Fantabulum** [comment]
> 
> 
> For name with space character you need to use backslash `\` char as prefix:
> ex: java.lang:name=G1 Old Gen,type=MemoryPool **->** java.lang:name=G1\ Old\ Gen,type=MemoryPool

Testing on windows terminal, I had to double escape:
ex: java.lang:name=PS\\ Old\\ Gen,type=MemoryPool

**Comment by febelectron** [comment]
> Testing on windows terminal, I had to double escape:
> ex: java.lang:name=PS\\ Old\\ Gen,type=MemoryPool

Only this solution worked in Linux terminal

**Comment by ilyaevseev** [comment]
Linux + Docker + jmxterm:
```
$>bean java.lang:name=PS\\ MarkSweep,type=GarbageCollector
#bean is set to java.lang:name=PS MarkSweep,type=GarbageCollector
```
Use double backslash, luke
