### ISSUE TITLE
Dependency on jconsole prevents operation on headless JVM

### ISSUE THREAD

**Issue by gregw** [jiaqi/jmxterm#45]
I'm trying to run jmxterm on a docker image that has a headless JVM installed. I get the following error:
```
root@51a832163f66:/var/lib/jetty# java -jar /jmxterm-1.0.0-uber.jar
Welcome to JMX terminal. Type "help" for available commands.
$>open 1
#UnsupportedOperationException: /usr/lib/jvm/java-8-openjdk-amd64/lib/jconsole.jar file is not found
```

Is there any way to run jmxterm on a headless JVM?

**Comment by jiaqi** [comment]
It relies on jconsole.jar to find local JVM pid 1 in your example. Without jconsole.jar in non-headless JVM, it can't connect a pid.

**Comment by jelmerk** [comment]
As a workaround you can pass the following properties to the java process

```
-Dcom.sun.management.jmxremote.port=9999 
-Dcom.sun.management.jmxremote.rmi.port=9999 
-Dcom.sun.management.jmxremote.ssl=false 
-Djava.rmi.server.hostname=localhost 
-Dcom.sun.management.jmxremote.authenticate=false
```

And then connect via

java -jar jmxterm-1.0.0-uber.jar service:jmx:rmi:///jndi/rmi://localhost:9999/jmxrmi
