### ISSUE TITLE
Can't run an operation with "-" or " " in an argument

### ISSUE THREAD

**Issue by fakeh** [jiaqi/jmxterm#6]
Hi, I have a JMX operation that takes a string that has spaces in it, if I try to, for example:

run runnableOperation "this is my argument"

I get:
Operation runnableOperation with 4 parameters doesn't exist in bean ....

Or, if my operation requires a - in the argument, the Commons-Cli parser fails:
# MalformedArgException: Apache Jakarta commons-cli couldn't parse arguments [ "ping, -c1, 192.168.1.20"]

Am I doing the right thing by putting my string arguments in " or is there another way? Is there a workaround?

Many thanks, otherwise JMXTerm is fantastic.
Dan.

**Comment by nehal-u-shah** [comment]
I am trying with a string that contains #. Anyone know how to pass a string containign #74
