### ISSUE TITLE
jmxterm left JMX connection open

### ISSUE THREAD

**Issue by velo** [jiaqi/jmxterm#65]
I'm using `jmxterm` to check if my services are running using something like this:

```
echo "get -s -b kafka.server:type=app-info version" | java -jar /usr/bin/jmxterm-1.0.0-uber.jar -l 127.0.0.1:10000 -n -e
```

As side effect, I'm seeing several (more than 20) threads `JMX server connection timeout XXX` on my service.

Seems jmxterm is not disconnecting.

https://github.com/jiaqi/jmxterm/blob/master/src/main/java/org/cyclopsgroup/jmxterm/boot/CliMain.java#L149

I see it does `close()` the session, but, doesn't `disconnected()` the fore mentioned session.

I will be submitting a patch shortly

**Comment by jiaqi** [comment]
Thanks.
