### ISSUE TITLE
New format for to display mbean and attribute value in single line

### ISSUE THREAD

**Issue by satishbellapu** [jiaqi/jmxterm#73]
I am looking for a new formatter which can display both the mbean + attribute value in a single line, so that it will be easy for to integrate the jmxterm in a background process to auto pull the jvm metrics on a periodic time.

**Comment by jiaqi** [comment]
I suppose the background process is some kind of script. Can the script do the formatting work?
There can be a variety of ways to display name and value in a single line such as
name=value
name:value
name="value"
name->value
name(value)
...
If possible I'd rather leave the flexibility to the caller.
