### ISSUE TITLE
Security issues in v1.0.1

### ISSUE THREAD

**Issue by Noly** [jiaqi/jmxterm#86]
Hi there 👋, we detect that the latest version uses a dependency with security issues:

> <artifactId>commons-beanutils</artifactId>
      <version>1.9.3</version>

I've seen that was updated in commit [7cb8f02](https://github.com/jiaqi/jmxterm/commit/7cb8f023cb8cce3a17338e938bf766c7114d1b22) but no release was triggered.

Do you have a release scheduled soon?

**Comment by smccauliff** [comment]
I also just ran into this issue as well.   Can you do a 1.0.2 release?

**Comment by Noly** [comment]
I close this topic since it has already been released: https://github.com/jiaqi/jmxterm/releases/tag/v1.0.2
