### ISSUE TITLE
How to track java.nio domain

### ISSUE THREAD

**Issue by khatwaniNikhil** [jiaqi/jmxterm#94]
Pls suggest 

$>beans
#domain = java.nio:
java.nio:name=direct,type=BufferPool
java.nio:name=mapped,type=BufferPool

$>bean java.nio:type=BufferPool
#IllegalArgumentException: Bean name java.nio:type=BufferPool isn't valid

**Comment by jiaqi** [comment]
It seems you didn't include `direct,` or `mapped,` in the name.
