### ISSUE TITLE
How can I list the bean childrens ?

### ISSUE THREAD

**Issue by webmyday** [jiaqi/jmxterm#96]
First thank you for this great tool, it helps a lot when you try to work from cli/ssh. 

I was trying to get the list of  jdbc configured datasources from a jboss as server and the jmx name should looks like this “jboss.as:subsystem=datasources,data-source=*” . Trying to use this in jmxterm returns:
$>info -b jboss.as:subsystem=datasources,data-source=*
#IllegalArgumentException: Bean name jboss.as:subsystem=datasources,data-source=* isn't valid
$>bean jboss.as:subsystem=datasources,data-source=*
#IllegalArgumentException: Bean name jboss.as:subsystem=datasources,data-source=* isn't valid

but I am able to get information if I select:

$>bean jboss.as:subsystem=datasources
#bean is set to jboss.as:subsystem=datasources
$>bean jboss.as:subsystem=datasources,data-source=ExampleDS,statistics=pool
#bean is set to jboss.as:subsystem=datasources,data-source=ExampleDS,statistics=pool

For mbean model and supported childrens please have a look on:
https://access.redhat.com/webassets/avalon/d/red_hat_jboss_enterprise_application_platform/7.3/mgmt_model/subsystem/datasources/index.html

There is another way to query for the list of childrens or how can I get the list of mbean childrens using jmxterm ?

Thank you in advance for the time and effort you put in this.

**Comment by jiaqi** [comment]
There isn't a bean named `jboss.as:subsystem=datasources,data-source=*`.
The closest thing is `beans -d jboss.as`.
